### ISSUE TITLE
Hobson is cooler than Chuck Norris

### ISSUE THREAD

**Issue by trshafer** [jaredatron/hobson#3]
Are you ok with this responsibility?

**Comment by jaredatron** [comment]
I'm incapable of being anything less then ok

**Comment by kylev** [comment]
:+1:

**Comment by jaredatron** [comment]
:neckbeard:

**Comment by trshafer** [comment]
I wanted to see if I could put together a "github citizen resume." So I found you can search github like this: https://github.com/search?q=author%3Agrowlsworth&type=Issues&utf8=%E2%9C%93 . This actually gives a pretty good idea about what people add to open source repos that they probably don't own. That lead me to this unresolved PR. It would be fun to make a little app that makes a nice github citizen infographic.

**Comment by jaredatron** [comment]
+1

On Mon, Jun 29, 2015 at 2:10 PM, Thomas Shafer notifications@github.com
wrote:

> I wanted to see if I could put together a "github citizen resume." So I
> found you can search github like this:
> https://github.com/search?q=author%3Agrowlsworth&type=Issues&utf8=%E2%9C%93
> . This actually gives a pretty good idea about what people add to open
> source repos that they probably don't own. That lead me to this unresolved
> PR. It would be fun to make a little app that makes a nice github citizen
> infographic.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/deadlyicon/hobson/issues/3#issuecomment-116847273.

## 

Jared
